# Generated by Django 6.0.3 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('advisor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('advisor_name', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
